version: '3.9'
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.staging
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: hospital_db_staging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
  celery:
    build: .
    command: celery -A config worker -l info
    env_file:
      - .env.staging
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A config beat -l info
    env_file:
      - .env.staging
    depends_on:
      - db
      - redis
  flower:
    image: mher/flower
    command: python3 -m flower --broker=redis://redis:6379/0 --port=5556
    ports:
      - "5556:5556"
    depends_on:
      - redis
      - celery
volumes:
  postgres_data_staging:
