services:
  - type: web
    name: hospital-backend
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-render-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: your-render-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
    healthCheckPath: /api/core/health/
